### ISSUE TITLE
doc error between height-75-ns and height-75

### ISSUE THREAD

**Issue by louis-pvs** [mkwng/tachyons-quiz#3]
![screen shot 2016-12-16 at 3 05 12 pm](https://cloud.githubusercontent.com/assets/7659194/21254585/38498736-c3a1-11e6-89c0-c6c307ad6cc2.png)
![screen shot 2016-12-16 at 3 05 26 pm](https://cloud.githubusercontent.com/assets/7659194/21254586/387bdc0e-c3a1-11e6-8ec7-23b38db95a6e.png)

**Comment by mkwng** [comment]
correct me if wrong, but `.h-75-ns` only applies to not small devices:
```css
.h-75 {height: 75%;}
@media (--breakpoint-not-small) {
   .h-75-ns {height: 75%;}
}
```
